version: "3.7"

services:

  app:
    build: ./app
    container_name: app
    restart: always
    expose:
      - 900

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:1234"